public enum ARIARole: String {
	// Widget roles
	case button = "button"
	case checkbox = "checkbox"
	case gridcell = "gridcell"
	case link = "link"
	case menuitem = "menuitem"
	case menuitemcheckbox = "menuitemcheckbox"
	case menuitemradio = "menuitemradio"
	case option = "option"
	case progressbar = "progressbar"
	case radio = "radio"
	case scrollbar = "scrollbar"
	case searchbox = "searchbox"
	case separator = "separator"
	case slider = "slider"
	case spinbutton = "spinbutton"
	case `switch` = "switch"
	case tab = "tab"
	case tabpanel = "tabpanel"
	case textbox = "textbox"
	case treeitem = "treeitem"

	// Composite widget roles
	case combobox = "combobox"
	case grid = "grid"
	case listbox = "listbox"
	case menu = "menu"
	case menubar = "menubar"
	case radiogroup = "radiogroup"
	case tablist = "tablist"
	case tree = "tree"
	case treegrid = "treegrid"

	// Document structure roles
	case application = "application"
	case article = "article"
	case cell = "cell"
	case columnheader = "columnheader"
	case definition = "definition"
	case directory = "directory"
	case document = "document"
	case feed = "feed"
	case figure = "figure"
	case group = "group"
	case heading = "heading"
	case img = "img"
	case list = "list"
	case listitem = "listitem"
	case math = "math"
	case none = "none"
	case note = "note"
	case presentation = "presentation"
	case row = "row"
	case rowgroup = "rowgroup"
	case rowheader = "rowheader"
	case table = "table"
	case term = "term"
	case toolbar = "toolbar"
	case tooltip = "tooltip"

	// Landmark roles
	case banner = "banner"
	case complementary = "complementary"
	case contentinfo = "contentinfo"
	case form = "form"
	case main = "main"
	case navigation = "navigation"
	case region = "region"
	case search = "search"

	// Live region roles
	case alert = "alert"
	case log = "log"
	case marquee = "marquee"
	case status = "status"
	case timer = "timer"

	// Window roles
	case alertdialog = "alertdialog"
	case dialog = "dialog"
}
