public enum CSSFlexFlow: String {
	case row = "row"
	case rowReverse = "row-reverse"
	case column = "column"
	case columnReverse = "column-reverse"
	case nowrap = "nowrap"
	case wrap = "wrap"
	case wrapReverse = "wrap-reverse"
	case rowNowrap = "row nowrap"
	case rowWrap = "row wrap"
	case rowWrapReverse = "row wrap-reverse"
	case rowReverseNowrap = "row-reverse nowrap"
	case rowReverseWrap = "row-reverse wrap"
	case rowReverseWrapReverse = "row-reverse wrap-reverse"
	case columnNowrap = "column nowrap"
	case columnWrap = "column wrap"
	case columnWrapReverse = "column wrap-reverse"
	case columnReverseNowrap = "column-reverse nowrap"
	case columnReverseWrap = "column-reverse wrap"
	case columnReverseWrapReverse = "column-reverse wrap-reverse"
}
