#if !os(WASI)

public struct HTMLInput {
	public enum `Type`: String {
		case text = "text"
		case password = "password"
		case email = "email"
		case number = "number"
		case tel = "tel"
		case url = "url"
		case search = "search"
		case date = "date"
		case time = "time"
		case datetimeLocal = "datetime-local"
		case month = "month"
		case week = "week"
		case color = "color"
		case file = "file"
		case hidden = "hidden"
		case image = "image"
		case checkbox = "checkbox"
		case radio = "radio"
		case range = "range"
		case submit = "submit"
		case reset = "reset"
		// case button = "button" (!: use HTMLButton.Button instead of this)
	}

	public enum Autocomplete: String {
		case off = "off"
		case on = "on"
		case name = "name"
		case honorificPrefix = "honorific-prefix"
		case givenName = "given-name"
		case additionalName = "additional-name"
		case familyName = "family-name"
		case honorificSuffix = "honorific-suffix"
		case nickname = "nickname"
		case email = "email"
		case username = "username"
		case newPassword = "new-password"
		case currentPassword = "current-password"
		case oneTimeCode = "one-time-code"
		case organizationTitle = "organization-title"
		case organization = "organization"
		case streetAddress = "street-address"
		case addressLine1 = "address-line1"
		case addressLine2 = "address-line2"
		case addressLine3 = "address-line3"
		case addressLevel4 = "address-level4"
		case addressLevel3 = "address-level3"
		case addressLevel2 = "address-level2"
		case addressLevel1 = "address-level1"
		case country = "country"
		case countryName = "country-name"
		case postalCode = "postal-code"
		case ccName = "cc-name"
		case ccGivenName = "cc-given-name"
		case ccAdditionalName = "cc-additional-name"
		case ccFamilyName = "cc-family-name"
		case ccNumber = "cc-number"
		case ccExp = "cc-exp"
		case ccExpMonth = "cc-exp-month"
		case ccExpYear = "cc-exp-year"
		case ccCsc = "cc-csc"
		case ccType = "cc-type"
		case transactionCurrency = "transaction-currency"
		case transactionAmount = "transaction-amount"
		case language = "language"
		case bday = "bday"
		case bdayDay = "bday-day"
		case bdayMonth = "bday-month"
		case bdayYear = "bday-year"
		case sex = "sex"
		case tel = "tel"
		case telCountryCode = "tel-country-code"
		case telNational = "tel-national"
		case telAreaCode = "tel-area-code"
		case telLocal = "tel-local"
		case telExtension = "tel-extension"
		case impp = "impp"
		case url = "url"
		case photo = "photo"
	}
}

#endif
