public enum SVGAttributeName: String, Sendable {
	case d = "d"
	case transform = "transform"
	case fill = "fill"
	case fillOpacity = "fill-opacity"
	case stroke = "stroke"
	case strokeWidth = "stroke-width"
	case x = "x"
	case y = "y"
	case width = "width"
	case height = "height"
	case opacity = "opacity"
	case rx = "rx"
	case ry = "ry"
	case cx = "cx"
	case cy = "cy"
	case r = "r"
	case points = "points"
	case visibility = "visibility"
}
