public enum SVGAttributeName: String, Sendable {
	case d = "d"
	case transform = "transform"
	case fill = "fill"
	case fillOpacity = "fill-opacity"
	case stroke = "stroke"
	case strokeWidth = "stroke-width"
	case x = "x"
	case y = "y"
	case x1 = "x1"
	case y1 = "y1"
	case x2 = "x2"
	case y2 = "y2"
	case width = "width"
	case height = "height"
	case opacity = "opacity"
	case rx = "rx"
	case ry = "ry"
	case cx = "cx"
	case cy = "cy"
	case r = "r"
	case points = "points"
	case visibility = "visibility"
	case offset = "offset"
}
